sudo: required

language: csharp

services:
  - docker

before_install:
  - docker build -t magick_builder_amzn .

script:
  - chmod +x make_magick.sh
  - ./make_magick.sh $magick_tag $magick_quantum $magick_hdri